# Generated by Django 3.0.4 on 2020-03-11 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20200311_2331'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='professorrating',
            unique_together=set(),
        ),
    ]
