# Generated by Django 3.0.4 on 2020-03-12 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0008_auto_20200311_2344'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='professorrating',
            unique_together=set(),
        ),
    ]
