# Generated by Django 3.0.4 on 2020-03-12 00:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rate', '0009_auto_20200312_0018'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='professorrating',
            unique_together={('professor', 'module_state', 'user')},
        ),
    ]
