# Generated by Django 3.0.4 on 2020-03-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0010_auto_20200312_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='modulestate',
            unique_together={('module', 'year', 'semester')},
        ),
    ]
